# Generated by Django 5.0 on 2023-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0002_alter_data_age_alter_data_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gender',
            field=models.TextField(default=True),
        ),
    ]
