# Generated by Django 5.0 on 2023-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0003_alter_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dob',
            field=models.DateField(),
        ),
    ]
