# Generated by Django 5.0 on 2023-12-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0004_alter_data_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='material',
        ),
        migrations.AddField(
            model_name='data',
            name='material',
            field=models.ManyToManyField(blank=True, to='bankapp2.material'),
        ),
    ]
