# Generated by Django 5.0 on 2023-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0006_alter_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='account',
            field=models.CharField(choices=[('default', 'Default'), ('current', 'Current'), ('savings', 'Savings')], default='default', max_length=15),
        ),
    ]
