# Generated by Django 5.0 on 2023-12-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0007_alter_data_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='account',
            field=models.CharField(choices=[('type', 'Type'), ('savings', 'Savings'), ('current', 'Current')], default='type', max_length=20),
        ),
    ]
