# Generated by Django 5.0 on 2023-12-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0008_alter_data_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='account',
        ),
    ]
