# Generated by Django 5.0 on 2023-12-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp2', '0009_remove_data_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp2.type'),
        ),
    ]
